import type { ActiveDirectoryAuthenticatorConfiguration, ADWebAuthAuthenticatorConfiguration, FunctionAuthenticatorConfiguration, PlainTextAuthenticatorConfiguration } from '@cityssm/authentication-helper';
import type { config as MSSQLConfig } from 'mssql';
import type { NtfyTopic } from '../integrations/ntfy/types.js';
import type { ConfigBurialSiteNameSegments, DynamicsGPLookup } from '../types/config.types.js';
export declare const configDefaultValues: {
    'application.applicationName': string;
    'application.applicationUrl': string | undefined;
    'application.backgroundUrl': string;
    'application.httpPort': number;
    'application.logoUrl': string;
    'application.maximumProcesses': number;
    'application.useTestDatabases': boolean;
    'application.attachmentsPath': string;
    'application.maxAttachmentFileSize': number;
    'login.authentication': {
        config: ActiveDirectoryAuthenticatorConfiguration;
        type: "activeDirectory";
    } | {
        config: ADWebAuthAuthenticatorConfiguration;
        type: "adWebAuth";
    } | {
        config: FunctionAuthenticatorConfiguration;
        type: "function";
    } | {
        config: PlainTextAuthenticatorConfiguration;
        type: "plainText";
    } | undefined;
    'login.domain': string;
    'reverseProxy.disableCompression': boolean;
    'reverseProxy.disableEtag': boolean;
    'reverseProxy.disableRateLimit': boolean;
    'reverseProxy.trafficIsForwarded': boolean;
    'reverseProxy.urlPrefix': string;
    'session.cookieName': string;
    'session.doKeepAlive': boolean;
    'session.maxAgeMillis': number;
    'session.secret': string;
    'users.canLogin': string[];
    'users.canUpdate': string[];
    'users.canUpdateCemeteries': string[];
    'users.canUpdateContracts': string[];
    'users.canUpdateWorkOrders': string[];
    'users.isAdmin': string[];
    'users.testing': string[];
    'settings.customizationsPath': string;
    'settings.latitudeMax': number;
    'settings.latitudeMin': number;
    'settings.longitudeMax': number;
    'settings.longitudeMin': number;
    'settings.cemeteries.refreshImageChanges': boolean;
    'settings.burialSites.burialSiteNameSegments': ConfigBurialSiteNameSegments;
    'settings.burialSites.burialSiteNameSegments.includeCemeteryKey': boolean;
    'settings.burialSites.refreshImageChanges': boolean;
    'settings.contracts.burialSiteIdIsRequired': boolean;
    'settings.contracts.contractNumberLength': number;
    'settings.contracts.contractEndDateIsAvailable': boolean;
    'settings.contracts.contractEndDateIsRequired': boolean;
    'settings.contracts.prints': string[];
    'settings.fees.taxPercentageDefault': number;
    'settings.workOrders.workOrderNumberLength': number;
    'settings.workOrders.calendarEmailAddress': string;
    'settings.workOrders.prints': string[];
    'settings.adminCleanup.recordDeleteAgeDays': number;
    'settings.printPdf.browser': "chrome" | "firefox";
    'settings.printPdf.contentDisposition': "attachment" | "inline";
    'settings.databaseBackup.taskIsEnabled': boolean;
    'settings.databaseBackup.backupHour': number;
    'settings.databaseBackup.deleteAgeDays': number;
    'integrations.dynamicsGP.integrationIsEnabled': boolean;
    'integrations.dynamicsGP.mssqlConfig': MSSQLConfig;
    'integrations.dynamicsGP.lookupOrder': DynamicsGPLookup[];
    'integrations.dynamicsGP.accountCodes': string[];
    'integrations.dynamicsGP.itemNumbers': string[];
    'integrations.dynamicsGP.trialBalanceCodes': string[];
    'integrations.consignoCloud.integrationIsEnabled': boolean;
    'integrations.consignoCloud.apiKey': string;
    'integrations.consignoCloud.apiSecret': string;
    'integrations.consignoCloud.baseUrl': string;
    'integrations.ntfy.integrationIsEnabled': boolean;
    'integrations.ntfy.server': string;
    'integrations.ntfy.topics': Partial<Record<NtfyTopic, string>>;
};
export default configDefaultValues;
