import type { BurialSiteStatus, BurialSiteType, CommittalType, ContractType, ContractTypeField, IntermentContainerType, WorkOrderMilestoneType, WorkOrderType } from '../types/record.types.js';
export declare function getBurialSiteStatusByBurialSiteStatus(burialSiteStatus: string): BurialSiteStatus | undefined;
export declare function getBurialSiteStatusById(burialSiteStatusId: number): BurialSiteStatus | undefined;
export declare function getBurialSiteStatuses(): BurialSiteStatus[];
export declare function getBurialSiteTypeById(burialSiteTypeId: number): BurialSiteType | undefined;
export declare function getBurialSiteTypes(includeDeleted?: boolean): BurialSiteType[];
export declare function getBurialSiteTypesByBurialSiteType(burialSiteType: string, includeDeleted?: boolean): BurialSiteType | undefined;
export declare function getAllContractTypeFields(): ContractTypeField[];
export declare function getContractTypeByContractType(contractTypeString: string): ContractType | undefined;
export declare function getContractTypeById(contractTypeId: number): ContractType | undefined;
export declare function getContractTypePrintsById(contractTypeId: number): string[];
export declare function getContractTypes(): ContractType[];
export declare function getIntermentContainerTypeById(intermentContainerTypeId: number): IntermentContainerType | undefined;
export declare function getIntermentContainerTypes(): IntermentContainerType[];
export declare function getCommittalTypeById(committalTypeId: number): CommittalType | undefined;
export declare function getCommittalTypes(): CommittalType[];
export declare function getWorkOrderTypeById(workOrderTypeId: number): WorkOrderType | undefined;
export declare function getWorkOrderTypes(): WorkOrderType[];
export declare function getWorkOrderMilestoneTypeById(workOrderMilestoneTypeId: number): WorkOrderMilestoneType | undefined;
export declare function getWorkOrderMilestoneTypeByWorkOrderMilestoneType(workOrderMilestoneTypeString: string): WorkOrderMilestoneType | undefined;
export declare function getWorkOrderMilestoneTypes(): WorkOrderMilestoneType[];
export declare function preloadCaches(): void;
export declare const cacheTableNames: readonly ["BurialSiteStatuses", "BurialSiteTypeFields", "BurialSiteTypes", "CommittalTypes", "ContractTypeFields", "ContractTypePrints", "ContractTypes", "FeeCategories", "Fees", "IntermentContainerTypes", "WorkOrderMilestoneTypes", "WorkOrderTypes"];
export type CacheTableNames = typeof cacheTableNames[number];
export declare function clearCacheByTableName(tableName: CacheTableNames, relayMessage?: boolean): void;
export declare function clearCaches(): void;
