export const simpleReports = new Map([
    [
        'burialSiteComments-all',
        `
      SELECT
        *
      FROM
        BurialSiteComments
    `
    ],
    [
        'burialSiteFields-all',
        `
      SELECT
        *
      FROM
        BurialSiteFields
    `
    ],
    [
        'burialSites-all',
        `
      SELECT
        *
      FROM
        BurialSites
    `
    ],
    [
        'burialSiteStatuses-all',
        `
      SELECT
        *
      FROM
        BurialSiteStatuses
    `
    ],
    [
        'burialSiteTypeFields-all',
        `
      SELECT
        *
      FROM
        BurialSiteTypeFields
    `
    ],
    [
        'burialSiteTypes-all',
        `
      SELECT
        *
      FROM
        BurialSiteTypes
    `
    ],
    [
        'cemeteries-all',
        `
      SELECT
        *
      FROM
        Cemeteries
    `
    ],
    [
        'cemeteries-formatted',
        `
      SELECT
        cemeteryName,
        cemeteryDescription,
        cemeteryAddress1,
        cemeteryAddress2,
        cemeteryCity,
        cemeteryProvince,
        cemeteryPostalCode,
        cemeteryPhoneNumber
      FROM
        Cemeteries
      WHERE
        recordDelete_timeMillis IS NULL
      ORDER BY
        cemeteryName
    `
    ],
    [
        'committalTypes-all',
        `
      SELECT
        *
      FROM
        CommittalTypes
    `
    ],
    [
        'contractAttachments-all',
        `
      SELECT
        *
      FROM
        ContractAttachments
    `
    ],
    [
        'contractComments-all',
        `
      SELECT
        *
      FROM
        ContractComments
    `
    ],
    [
        'contractFees-all',
        `
      SELECT
        *
      FROM
        ContractFees
    `
    ],
    [
        'contractFields-all',
        `
      SELECT
        *
      FROM
        ContractFields
    `
    ],
    [
        'contractInterments-all',
        `
      SELECT
        *
      FROM
        ContractInterments
    `
    ],
    [
        'contractMetadata-all',
        `
      SELECT
        *
      FROM
        ContractMetadata
    `
    ],
    [
        'contracts-all',
        `
      SELECT
        *
      FROM
        Contracts
    `
    ],
    [
        'contractServiceTypes-all',
        `
      SELECT
        *
      FROM
        ContractServiceTypes
    `
    ],
    [
        'contractTransactions-all',
        `
      SELECT
        *
      FROM
        ContractTransactions
    `
    ],
    [
        'contractTypeFields-all',
        `
      SELECT
        *
      FROM
        ContractTypeFields
    `
    ],
    [
        'contractTypePrints-all',
        `
      SELECT
        *
      FROM
        ContractTypePrints
    `
    ],
    [
        'contractTypes-all',
        `
      SELECT
        *
      FROM
        ContractTypes
    `
    ],
    [
        'feeCategories-all',
        `
      SELECT
        *
      FROM
        FeeCategories
    `
    ],
    [
        'fees-all',
        `
      SELECT
        *
      FROM
        Fees
    `
    ],
    [
        'funeralHomes-all',
        `
      SELECT
        *
      FROM
        FuneralHomes
    `
    ],
    [
        'funeralHomes-formatted',
        `
      SELECT
        funeralHomeName,
        funeralHomeAddress1,
        funeralHomeAddress2,
        funeralHomeCity,
        funeralHomeProvince,
        funeralHomePostalCode,
        funeralHomePhoneNumber
      FROM
        FuneralHomes
      WHERE
        recordDelete_timeMillis IS NULL
    `
    ],
    [
        'intermentContainerTypes-all',
        `
      SELECT
        *
      FROM
        IntermentContainerTypes
    `
    ],
    [
        'intermentDepths-all',
        `
      SELECT
        *
      FROM
        IntermentDepths
    `
    ],
    [
        'serviceTypes-all',
        `
      SELECT
        *
      FROM
        ServiceTypes
    `
    ],
    [
        'workOrderBurialSites-all',
        `
      SELECT
        *
      FROM
        WorkOrderBurialSites
    `
    ],
    [
        'workOrderComments-all',
        `
      SELECT
        *
      FROM
        WorkOrderComments
    `
    ],
    [
        'workOrderMilestones-all',
        `
      SELECT
        *
      FROM
        WorkOrderMilestones
    `
    ],
    [
        'workOrderMilestoneTypes-all',
        `
      SELECT
        *
      FROM
        WorkOrderMilestoneTypes
    `
    ],
    [
        'workOrders-all',
        `
      SELECT
        *
      FROM
        WorkOrders
    `
    ],
    [
        'workOrderTypes-all',
        `
      SELECT
        *
      FROM
        WorkOrderTypes
    `
    ]
]);
