import { DEBUG_ENABLE_NAMESPACES as DEBUG_ENABLE_NAMESPACES_CONSIGNO_CLOUD } from '@cityssm/consigno-cloud-api/debug'
import { DEBUG_ENABLE_NAMESPACES as DEBUG_ENABLE_NAMESPACES_DYNAMICS } from '@cityssm/dynamics-gp/debug'
import { DEBUG_ENABLE_NAMESPACES as DEBUG_ENABLE_NAMESPACES_PDF_PUPPETEER } from '@cityssm/pdf-puppeteer/debug'
import { DEBUG_ENABLE_NAMESPACES as DEBUG_ENABLE_NAMESPACES_SCHEDULED_TASK } from '@cityssm/scheduled-task/debug'

export const DEBUG_NAMESPACE = 'sunrise'

export const DEBUG_ENABLE_NAMESPACES = [
  `${DEBUG_NAMESPACE}:*`,
  DEBUG_ENABLE_NAMESPACES_CONSIGNO_CLOUD,
  DEBUG_ENABLE_NAMESPACES_DYNAMICS,
  DEBUG_ENABLE_NAMESPACES_PDF_PUPPETEER,
  DEBUG_ENABLE_NAMESPACES_SCHEDULED_TASK
].join(',')

export const PROCESS_ID_MAX_DIGITS = 5