#!/usr/bin/env node

/* eslint-disable no-secrets/no-secrets */

import Debug from 'debug'
import meow from 'meow'

import { DEBUG_ENABLE_NAMESPACES, DEBUG_NAMESPACE } from '../../debug.config.js'

const cli = meow(
  `
  Usage
    $ npm run cli:findAGraveMemorialExtractorImport -- <cemeteryId> <pathToCsvFile>

  Options
    --showDebug  Show debug output

  Examples
    $ npm run cli:findAGraveMemorialExtractorImport -- 123 ./graveMemorials.csv
`,
  {
    description: `
    Updates Sunrise CMS at-need contracts with Find a Grave memorial data from an exported CSV file,
    generated by the Find a Grave Memorial Extractor browser extension.
    Updates are made in the testing database.`,

    importMeta: import.meta,

    autoHelp: true,
    flags: {
      showDebug: {
        type: 'boolean',
        default: false,
        description: 'Show debug output'
      }
    }
  }
)

if (cli.input.length !== 2) {
  cli.showHelp()
}

if (cli.flags.showDebug) {
  Debug.enable(DEBUG_ENABLE_NAMESPACES)

  Debug(`${DEBUG_NAMESPACE}:findAGraveMemorialExtractorImport:cli`)(
    'Debug output enabled'
  )
}

const [cemeteryId, pathToCsvFile] = cli.input

/*
 * Import and run the Find a Grave Memorial Extractor Import function.
 */

const runFindAGraveMemorialExtractorImport = await import('./import.js')

await runFindAGraveMemorialExtractorImport.default(cemeteryId, pathToCsvFile)
