import type { NextFunction, Request, Response } from 'express';
export declare function adminGetHandler(request: Request, response: Response, next: NextFunction): void;
export declare function adminPostHandler(request: Request, response: Response, next: NextFunction): void;
export declare function apiGetHandler(request: Request, response: Response, next: NextFunction): void;
export declare function updateCemeteriesGetHandler(request: Request, response: Response, next: NextFunction): void;
export declare function updateCemeteriesPostHandler(request: Request, response: Response, next: NextFunction): void;
export declare function updateContractsGetHandler(request: Request, response: Response, next: NextFunction): void;
export declare function updateContractsPostHandler(request: Request, response: Response, next: NextFunction): void;
export declare function updateWorkOrdersGetHandler(request: Request, response: Response, next: NextFunction): void;
export declare function updateWorkOrdersPostHandler(request: Request, response: Response, next: NextFunction): void;
