import { type DateString } from '@cityssm/utils-datetime';
import type { PoolConnection } from 'better-sqlite-pool';
export interface AddContractForm {
    contractTypeId: string | number;
    burialSiteId: string | number;
    contractStartDateString: DateString | '';
    contractEndDateString: DateString | '';
    contractTypeFieldIds?: string;
    [fieldValue_contractTypeFieldId: `fieldValue_${string}`]: unknown;
    purchaserName?: string;
    purchaserAddress1?: string;
    purchaserAddress2?: string;
    purchaserCity?: string;
    purchaserProvince?: string;
    purchaserPostalCode?: string;
    purchaserPhoneNumber?: string;
    purchaserEmail?: string;
    purchaserRelationship?: string;
    funeralHomeId?: string | number;
    funeralDirectorName?: string;
    deceasedName?: string;
    deceasedAddress1?: string;
    deceasedAddress2?: string;
    deceasedCity?: string;
    deceasedProvince?: string;
    deceasedPostalCode?: string;
    birthDateString?: DateString | '';
    birthPlace?: string;
    deathDateString?: DateString | '';
    deathPlace?: string;
    intermentDateString?: DateString | '';
    intermentContainerTypeId?: string | number;
    intermentCommittalTypeId?: string | number;
}
export default function addContract(addForm: AddContractForm, user: User, connectedDatabase?: PoolConnection): Promise<number>;
