import { type DateString, type TimeString } from '@cityssm/utils-datetime';
import sqlite from 'better-sqlite3';
export interface AddContractForm {
    burialSiteId: number | string;
    contractEndDateString: '' | DateString;
    contractStartDateString: '' | DateString;
    contractTypeId: number | string;
    [fieldValue_contractTypeFieldId: `fieldValue_${string}`]: unknown;
    contractTypeFieldIds?: string;
    committalTypeId?: number | string;
    directionOfArrival?: string;
    funeralDateString?: '' | DateString;
    funeralDirectorName?: string;
    funeralHomeId?: '' | 'new' | `${number}` | number;
    funeralTimeString?: '' | TimeString;
    funeralHomeAddress1?: string;
    funeralHomeAddress2?: string;
    funeralHomeCity?: string;
    funeralHomeName?: string;
    funeralHomePhoneNumber?: string;
    funeralHomePostalCode?: string;
    funeralHomeProvince?: string;
    purchaserAddress1?: string;
    purchaserAddress2?: string;
    purchaserCity?: string;
    purchaserEmail?: string;
    purchaserName?: string;
    purchaserPhoneNumber?: string;
    purchaserPostalCode?: string;
    purchaserProvince?: string;
    purchaserRelationship?: string;
    birthDateString?: '' | DateString;
    birthPlace?: string;
    deathAge?: string;
    deathAgePeriod?: string;
    deathDateString?: '' | DateString;
    deathPlace?: string;
    deceasedAddress1?: string;
    deceasedAddress2?: string;
    deceasedCity?: string;
    deceasedName?: string;
    deceasedPostalCode?: string;
    deceasedProvince?: string;
    intermentContainerTypeId?: number | string;
}
export default function addContract(addForm: AddContractForm, user: User, connectedDatabase?: sqlite.Database): number;
