import type { ContractType } from '../../types/record.types.js';
export declare const availableBurialSiteStatusId: number;
export declare const reservedBurialSiteStatusId: number;
export declare const occupiedBurialSiteStatusId: number;
export declare const preneedContractType: ContractType;
export declare const intermentContractType: ContractType;
export declare const intermentDepthContractField: import("../../types/record.types.js").ContractTypeField | undefined;
export declare const cremationContractType: ContractType;
export declare const acknowledgedWorkOrderMilestoneTypeId: number | undefined;
export declare const deathWorkOrderMilestoneTypeId: number | undefined;
export declare const funeralWorkOrderMilestoneTypeId: number | undefined;
export declare const cremationWorkOrderMilestoneTypeId: number | undefined;
export declare const intermentWorkOrderMilestoneTypeId: number | undefined;
export declare const workOrderTypeId = 1;
