import type { ContractType } from '../../types/record.types.js';
export declare const availableBurialSiteStatusId: number;
export declare const reservedBurialSiteStatusId: number;
export declare const occupiedBurialSiteStatusId: number;
export declare const preneedContractType: ContractType;
export declare const atNeedContractType: ContractType;
export declare const permitOnlyContractType: ContractType;
export declare const intermentServiceTypeId: number;
export declare const cremationServiceTypeId: number;
export declare const entombmentServiceTypeId: number;
export declare const nicheServiceTypeId: number;
export declare const disintermentServiceTypeId: number;
export declare const acknowledgedWorkOrderMilestoneTypeId: number | undefined;
export declare const deathWorkOrderMilestoneTypeId: number | undefined;
export declare const funeralWorkOrderMilestoneTypeId: number | undefined;
export declare const cremationWorkOrderMilestoneTypeId: number | undefined;
export declare const intermentWorkOrderMilestoneTypeId: number | undefined;
export declare const workOrderTypeId = 1;
